/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */
/* Source: protocol/waywallen_ipc_v1.xml */

#ifndef WAYWALLEN_PROTO_H
#define WAYWALLEN_PROTO_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WW_PROTOCOL_NAME    "waywallen-ipc-v1"
#define WW_PROTOCOL_VERSION 1

/* --- Shared primitive types --- */

typedef struct ww_rect {
    float x;
    float y;
    float w;
    float h;
} ww_rect_t;

typedef struct ww_array_u32 {
    uint32_t count;
    uint32_t *data;    /* heap-allocated by decoder; NULL if count==0 */
} ww_array_u32_t;

typedef struct ww_array_u64 {
    uint32_t count;
    uint64_t *data;
} ww_array_u64_t;

typedef struct ww_array_i32 {
    uint32_t count;
    int32_t *data;
} ww_array_i32_t;

typedef struct ww_array_i64 {
    uint32_t count;
    int64_t *data;
} ww_array_i64_t;

typedef struct ww_array_f32 {
    uint32_t count;
    float *data;
} ww_array_f32_t;

typedef struct ww_array_f64 {
    uint32_t count;
    double *data;
} ww_array_f64_t;

typedef struct ww_array_string {
    uint32_t count;
    char **data;       /* each entry NUL-terminated, heap-allocated */
} ww_array_string_t;

typedef struct ww_kv {
    char *key;
    char *value;
} ww_kv_t;

typedef struct ww_kv_list {
    uint32_t count;
    ww_kv_t *data;
} ww_kv_list_t;

/* --- Codec buffer + return codes --- */

typedef struct ww_buf {
    uint8_t *data;
    size_t len;
    size_t cap;
} ww_buf_t;

/* Return codes: 0 = success, negative = -errno-ish. */
#define WW_OK                  0
#define WW_ERR_SHORT           (-1)   /* buffer truncated */
#define WW_ERR_BAD_STRING      (-2)   /* malformed length-prefixed string */
#define WW_ERR_BAD_ARRAY       (-3)   /* array length overflow */
#define WW_ERR_TRAILING        (-4)   /* unexpected trailing bytes */
#define WW_ERR_UNKNOWN_OPCODE  (-5)
#define WW_ERR_NOMEM           (-6)
#define WW_ERR_OVERFLOW        (-7)   /* frame bigger than u16 can address */

/* --- Opcodes --- */

typedef enum ww_event_in_op {
    WW_EVT_IN_INIT = 1,
    WW_EVT_IN_SETTING_CHANGED = 2,
    WW_EVT_IN_PLAY = 3,
    WW_EVT_IN_PAUSE = 4,
    WW_EVT_IN_POINTER_MOTION = 5,
    WW_EVT_IN_SET_FPS = 6,
    WW_EVT_IN_SHUTDOWN = 7,
    WW_EVT_IN_NEGOTIATE_BUFFERS = 9,
    WW_EVT_IN_POINTER_BUTTON = 10,
    WW_EVT_IN_POINTER_AXIS = 11,
} ww_event_in_op_t;

typedef enum ww_event_op {
    WW_EVT_READY = 1,
    WW_EVT_BIND_BUFFERS = 2,
    WW_EVT_FRAME_READY = 3,
    WW_EVT_ERROR = 4,
    WW_EVT_RELEASE_SYNCOBJ = 5,
    WW_EVT_FORMAT_CAPS = 6,
    WW_EVT_BIND_FAILED = 7,
    WW_EVT_INIT_NACK = 8,
    WW_EVT_REPORT_STATE = 9,
} ww_event_op_t;

typedef struct ww_evt_in_init_t {
    uint32_t spawn_version;
    uint32_t extent_w;
    uint32_t extent_h;
    uint32_t extent_mode;
    ww_kv_list_t settings;
    char *user_properties;
} ww_evt_in_init_t;

typedef struct ww_evt_in_setting_changed_t {
    ww_kv_list_t settings;
} ww_evt_in_setting_changed_t;

typedef struct ww_evt_in_play_t {
    int _empty; /* C forbids empty structs */
} ww_evt_in_play_t;

typedef struct ww_evt_in_pause_t {
    int _empty; /* C forbids empty structs */
} ww_evt_in_pause_t;

typedef struct ww_evt_in_pointer_motion_t {
    float x;
    float y;
    uint64_t timestamp_us;
    uint32_t modifiers;
} ww_evt_in_pointer_motion_t;

typedef struct ww_evt_in_set_fps_t {
    uint32_t fps;
} ww_evt_in_set_fps_t;

typedef struct ww_evt_in_shutdown_t {
    int _empty; /* C forbids empty structs */
} ww_evt_in_shutdown_t;

typedef struct ww_evt_in_negotiate_buffers_t {
    uint32_t fourcc;
    uint64_t modifier;
    uint32_t plane_count;
    uint32_t sync_mode;
    uint32_t color;
    uint32_t mem_hint;
    uint32_t count;
    uint32_t path;
    uint32_t mem_source;
} ww_evt_in_negotiate_buffers_t;

typedef struct ww_evt_in_pointer_button_t {
    float x;
    float y;
    uint32_t button;
    uint32_t state;
    uint64_t timestamp_us;
    uint32_t modifiers;
} ww_evt_in_pointer_button_t;

typedef struct ww_evt_in_pointer_axis_t {
    float x;
    float y;
    float delta_x;
    float delta_y;
    uint32_t source;
    uint64_t timestamp_us;
    uint32_t modifiers;
} ww_evt_in_pointer_axis_t;

typedef struct ww_evt_ready_t {
    uint32_t drm_render_major;
    uint32_t drm_render_minor;
} ww_evt_ready_t;

typedef struct ww_evt_bind_buffers_t {
    uint64_t generation;
    uint32_t flags;
    uint32_t count;
    uint32_t fourcc;
    uint32_t width;
    uint32_t height;
    uint64_t modifier;
    uint32_t planes_per_buffer;
    ww_array_u32_t stride;
    ww_array_u32_t plane_offset;
    ww_array_u64_t size;
} ww_evt_bind_buffers_t;

typedef struct ww_evt_frame_ready_t {
    uint32_t image_index;
    uint64_t seq;
    uint64_t ts_ns;
    uint64_t release_point;
} ww_evt_frame_ready_t;

typedef struct ww_evt_error_t {
    char *msg;
} ww_evt_error_t;

typedef struct ww_evt_release_syncobj_t {
    int _empty; /* C forbids empty structs */
} ww_evt_release_syncobj_t;

typedef struct ww_evt_format_caps_t {
    ww_array_u32_t fourccs;
    ww_array_u32_t mod_counts;
    ww_array_u64_t modifiers;
    ww_array_u32_t plane_counts;
    ww_array_u32_t device_uuid;
    ww_array_u32_t driver_uuid;
    uint32_t drm_render_major;
    uint32_t drm_render_minor;
    uint32_t mem_hints;
    uint32_t sync_caps;
    uint32_t color_caps;
    uint32_t extent_max_w;
    uint32_t extent_max_h;
} ww_evt_format_caps_t;

typedef struct ww_evt_bind_failed_t {
    uint32_t fourcc;
    uint64_t modifier;
    uint32_t reason;
    char *message;
} ww_evt_bind_failed_t;

typedef struct ww_evt_init_nack_t {
    uint32_t received_spawn_version;
    uint32_t supported_spawn_version;
    char *reason;
} ww_evt_init_nack_t;

typedef struct ww_evt_report_state_t {
    ww_kv_list_t state;
} ww_evt_report_state_t;

/* --- Per-message functions ---
 * encode:        append wire body to `out` (header is the caller's job)
 * decode:        consume `len` bytes; on success owns heap allocations
 * free:          release any heap fields the decoder populated
 * expected_fds:  how many SCM_RIGHTS fds the wire frame must carry
 */

int  ww_evt_in_init_encode(const ww_evt_in_init_t *m, ww_buf_t *out);
int  ww_evt_in_init_decode(const uint8_t *buf, size_t len, ww_evt_in_init_t *out);
void ww_evt_in_init_free(ww_evt_in_init_t *m);
uint32_t ww_evt_in_init_expected_fds(const ww_evt_in_init_t *m);

int  ww_evt_in_setting_changed_encode(const ww_evt_in_setting_changed_t *m, ww_buf_t *out);
int  ww_evt_in_setting_changed_decode(const uint8_t *buf, size_t len, ww_evt_in_setting_changed_t *out);
void ww_evt_in_setting_changed_free(ww_evt_in_setting_changed_t *m);
uint32_t ww_evt_in_setting_changed_expected_fds(const ww_evt_in_setting_changed_t *m);

int  ww_evt_in_play_encode(const ww_evt_in_play_t *m, ww_buf_t *out);
int  ww_evt_in_play_decode(const uint8_t *buf, size_t len, ww_evt_in_play_t *out);
void ww_evt_in_play_free(ww_evt_in_play_t *m);
uint32_t ww_evt_in_play_expected_fds(const ww_evt_in_play_t *m);

int  ww_evt_in_pause_encode(const ww_evt_in_pause_t *m, ww_buf_t *out);
int  ww_evt_in_pause_decode(const uint8_t *buf, size_t len, ww_evt_in_pause_t *out);
void ww_evt_in_pause_free(ww_evt_in_pause_t *m);
uint32_t ww_evt_in_pause_expected_fds(const ww_evt_in_pause_t *m);

int  ww_evt_in_pointer_motion_encode(const ww_evt_in_pointer_motion_t *m, ww_buf_t *out);
int  ww_evt_in_pointer_motion_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_motion_t *out);
void ww_evt_in_pointer_motion_free(ww_evt_in_pointer_motion_t *m);
uint32_t ww_evt_in_pointer_motion_expected_fds(const ww_evt_in_pointer_motion_t *m);

int  ww_evt_in_set_fps_encode(const ww_evt_in_set_fps_t *m, ww_buf_t *out);
int  ww_evt_in_set_fps_decode(const uint8_t *buf, size_t len, ww_evt_in_set_fps_t *out);
void ww_evt_in_set_fps_free(ww_evt_in_set_fps_t *m);
uint32_t ww_evt_in_set_fps_expected_fds(const ww_evt_in_set_fps_t *m);

int  ww_evt_in_shutdown_encode(const ww_evt_in_shutdown_t *m, ww_buf_t *out);
int  ww_evt_in_shutdown_decode(const uint8_t *buf, size_t len, ww_evt_in_shutdown_t *out);
void ww_evt_in_shutdown_free(ww_evt_in_shutdown_t *m);
uint32_t ww_evt_in_shutdown_expected_fds(const ww_evt_in_shutdown_t *m);

int  ww_evt_in_negotiate_buffers_encode(const ww_evt_in_negotiate_buffers_t *m, ww_buf_t *out);
int  ww_evt_in_negotiate_buffers_decode(const uint8_t *buf, size_t len, ww_evt_in_negotiate_buffers_t *out);
void ww_evt_in_negotiate_buffers_free(ww_evt_in_negotiate_buffers_t *m);
uint32_t ww_evt_in_negotiate_buffers_expected_fds(const ww_evt_in_negotiate_buffers_t *m);

int  ww_evt_in_pointer_button_encode(const ww_evt_in_pointer_button_t *m, ww_buf_t *out);
int  ww_evt_in_pointer_button_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_button_t *out);
void ww_evt_in_pointer_button_free(ww_evt_in_pointer_button_t *m);
uint32_t ww_evt_in_pointer_button_expected_fds(const ww_evt_in_pointer_button_t *m);

int  ww_evt_in_pointer_axis_encode(const ww_evt_in_pointer_axis_t *m, ww_buf_t *out);
int  ww_evt_in_pointer_axis_decode(const uint8_t *buf, size_t len, ww_evt_in_pointer_axis_t *out);
void ww_evt_in_pointer_axis_free(ww_evt_in_pointer_axis_t *m);
uint32_t ww_evt_in_pointer_axis_expected_fds(const ww_evt_in_pointer_axis_t *m);

int  ww_evt_ready_encode(const ww_evt_ready_t *m, ww_buf_t *out);
int  ww_evt_ready_decode(const uint8_t *buf, size_t len, ww_evt_ready_t *out);
void ww_evt_ready_free(ww_evt_ready_t *m);
uint32_t ww_evt_ready_expected_fds(const ww_evt_ready_t *m);

int  ww_evt_bind_buffers_encode(const ww_evt_bind_buffers_t *m, ww_buf_t *out);
int  ww_evt_bind_buffers_decode(const uint8_t *buf, size_t len, ww_evt_bind_buffers_t *out);
void ww_evt_bind_buffers_free(ww_evt_bind_buffers_t *m);
uint32_t ww_evt_bind_buffers_expected_fds(const ww_evt_bind_buffers_t *m);

int  ww_evt_frame_ready_encode(const ww_evt_frame_ready_t *m, ww_buf_t *out);
int  ww_evt_frame_ready_decode(const uint8_t *buf, size_t len, ww_evt_frame_ready_t *out);
void ww_evt_frame_ready_free(ww_evt_frame_ready_t *m);
uint32_t ww_evt_frame_ready_expected_fds(const ww_evt_frame_ready_t *m);

int  ww_evt_error_encode(const ww_evt_error_t *m, ww_buf_t *out);
int  ww_evt_error_decode(const uint8_t *buf, size_t len, ww_evt_error_t *out);
void ww_evt_error_free(ww_evt_error_t *m);
uint32_t ww_evt_error_expected_fds(const ww_evt_error_t *m);

int  ww_evt_release_syncobj_encode(const ww_evt_release_syncobj_t *m, ww_buf_t *out);
int  ww_evt_release_syncobj_decode(const uint8_t *buf, size_t len, ww_evt_release_syncobj_t *out);
void ww_evt_release_syncobj_free(ww_evt_release_syncobj_t *m);
uint32_t ww_evt_release_syncobj_expected_fds(const ww_evt_release_syncobj_t *m);

int  ww_evt_format_caps_encode(const ww_evt_format_caps_t *m, ww_buf_t *out);
int  ww_evt_format_caps_decode(const uint8_t *buf, size_t len, ww_evt_format_caps_t *out);
void ww_evt_format_caps_free(ww_evt_format_caps_t *m);
uint32_t ww_evt_format_caps_expected_fds(const ww_evt_format_caps_t *m);

int  ww_evt_bind_failed_encode(const ww_evt_bind_failed_t *m, ww_buf_t *out);
int  ww_evt_bind_failed_decode(const uint8_t *buf, size_t len, ww_evt_bind_failed_t *out);
void ww_evt_bind_failed_free(ww_evt_bind_failed_t *m);
uint32_t ww_evt_bind_failed_expected_fds(const ww_evt_bind_failed_t *m);

int  ww_evt_init_nack_encode(const ww_evt_init_nack_t *m, ww_buf_t *out);
int  ww_evt_init_nack_decode(const uint8_t *buf, size_t len, ww_evt_init_nack_t *out);
void ww_evt_init_nack_free(ww_evt_init_nack_t *m);
uint32_t ww_evt_init_nack_expected_fds(const ww_evt_init_nack_t *m);

int  ww_evt_report_state_encode(const ww_evt_report_state_t *m, ww_buf_t *out);
int  ww_evt_report_state_decode(const uint8_t *buf, size_t len, ww_evt_report_state_t *out);
void ww_evt_report_state_free(ww_evt_report_state_t *m);
uint32_t ww_evt_report_state_expected_fds(const ww_evt_report_state_t *m);

/* --- Output buffer helpers --- */
void ww_buf_init(ww_buf_t *b);
void ww_buf_free(ww_buf_t *b);
int  ww_buf_reserve(ww_buf_t *b, size_t additional);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* WAYWALLEN_PROTO_H */
