// AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND.
// Source: protocol/waywallen_ipc_v1.xml

pub const PROTOCOL_NAME: &str = "waywallen-ipc-v1";
pub const PROTOCOL_VERSION: u32 = 1;

pub mod opcode {
    pub mod event_in {
        pub const INIT: u16 = 1;
        pub const SETTING_CHANGED: u16 = 2;
        pub const PLAY: u16 = 3;
        pub const PAUSE: u16 = 4;
        pub const POINTER_MOTION: u16 = 5;
        pub const SET_FPS: u16 = 6;
        pub const SHUTDOWN: u16 = 7;
        pub const NEGOTIATE_BUFFERS: u16 = 9;
        pub const POINTER_BUTTON: u16 = 10;
        pub const POINTER_AXIS: u16 = 11;
    }
    pub mod event {
        pub const READY: u16 = 1;
        pub const BIND_BUFFERS: u16 = 2;
        pub const FRAME_READY: u16 = 3;
        pub const ERROR: u16 = 4;
        pub const RELEASE_SYNCOBJ: u16 = 5;
        pub const FORMAT_CAPS: u16 = 6;
        pub const BIND_FAILED: u16 = 7;
        pub const INIT_NACK: u16 = 8;
        pub const REPORT_STATE: u16 = 9;
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Rect {
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

#[derive(Debug, Clone, PartialEq)]
pub enum DecodeError {
    TooShort,
    BadString,
    BadArrayLen,
    Trailing,
    UnknownOpcode(u16),
}

impl std::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooShort => write!(f, "message body too short"),
            Self::BadString => write!(f, "malformed string"),
            Self::BadArrayLen => write!(f, "array length overflow"),
            Self::Trailing => write!(f, "trailing bytes after decode"),
            Self::UnknownOpcode(op) => write!(f, "unknown opcode {op}"),
        }
    }
}

impl std::error::Error for DecodeError {}

mod wire {
    use super::{DecodeError, Rect};

    // ---- writers ----
    pub fn w_u32(buf: &mut Vec<u8>, v: u32) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_i32(buf: &mut Vec<u8>, v: i32) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_u64(buf: &mut Vec<u8>, v: u64) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_i64(buf: &mut Vec<u8>, v: i64) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_f32(buf: &mut Vec<u8>, v: f32) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_f64(buf: &mut Vec<u8>, v: f64) { buf.extend_from_slice(&v.to_le_bytes()); }
    pub fn w_rect(buf: &mut Vec<u8>, r: &Rect) {
        w_f32(buf, r.x); w_f32(buf, r.y); w_f32(buf, r.w); w_f32(buf, r.h);
    }
    pub fn pad4(buf: &mut Vec<u8>) {
        while buf.len() % 4 != 0 { buf.push(0); }
    }
    pub fn w_string(buf: &mut Vec<u8>, s: &str) {
        let len = s.len() as u32 + 1;
        w_u32(buf, len);
        buf.extend_from_slice(s.as_bytes());
        buf.push(0);
        pad4(buf);
    }
    pub fn w_array_u32(buf: &mut Vec<u8>, xs: &[u32]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_u32(buf, *v); }
    }
    pub fn w_array_i32(buf: &mut Vec<u8>, xs: &[i32]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_i32(buf, *v); }
    }
    pub fn w_array_u64(buf: &mut Vec<u8>, xs: &[u64]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_u64(buf, *v); }
    }
    pub fn w_array_i64(buf: &mut Vec<u8>, xs: &[i64]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_i64(buf, *v); }
    }
    pub fn w_array_f32(buf: &mut Vec<u8>, xs: &[f32]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_f32(buf, *v); }
    }
    pub fn w_array_f64(buf: &mut Vec<u8>, xs: &[f64]) {
        w_u32(buf, xs.len() as u32);
        for v in xs { w_f64(buf, *v); }
    }
    pub fn w_array_string(buf: &mut Vec<u8>, xs: &[String]) {
        w_u32(buf, xs.len() as u32);
        for s in xs { w_string(buf, s); }
    }
    pub fn w_kv_list(buf: &mut Vec<u8>, xs: &[(String, String)]) {
        w_u32(buf, xs.len() as u32);
        for (k, v) in xs {
            w_string(buf, k);
            w_string(buf, v);
        }
    }

    // ---- reader ----
    pub struct R<'a> { buf: &'a [u8], pos: usize }
    impl<'a> R<'a> {
        pub fn new(buf: &'a [u8]) -> Self { Self { buf, pos: 0 } }
        pub fn at_end(&self) -> bool { self.pos == self.buf.len() }
        fn take(&mut self, n: usize) -> Result<&'a [u8], DecodeError> {
            if self.buf.len() - self.pos < n { return Err(DecodeError::TooShort); }
            let out = &self.buf[self.pos..self.pos + n];
            self.pos += n;
            Ok(out)
        }
        pub fn u32(&mut self) -> Result<u32, DecodeError> {
            Ok(u32::from_le_bytes(self.take(4)?.try_into().unwrap()))
        }
        pub fn i32(&mut self) -> Result<i32, DecodeError> {
            Ok(i32::from_le_bytes(self.take(4)?.try_into().unwrap()))
        }
        pub fn u64(&mut self) -> Result<u64, DecodeError> {
            Ok(u64::from_le_bytes(self.take(8)?.try_into().unwrap()))
        }
        pub fn i64(&mut self) -> Result<i64, DecodeError> {
            Ok(i64::from_le_bytes(self.take(8)?.try_into().unwrap()))
        }
        pub fn f32(&mut self) -> Result<f32, DecodeError> {
            Ok(f32::from_le_bytes(self.take(4)?.try_into().unwrap()))
        }
        pub fn f64(&mut self) -> Result<f64, DecodeError> {
            Ok(f64::from_le_bytes(self.take(8)?.try_into().unwrap()))
        }
        pub fn rect(&mut self) -> Result<Rect, DecodeError> {
            Ok(Rect { x: self.f32()?, y: self.f32()?, w: self.f32()?, h: self.f32()? })
        }
        pub fn string(&mut self) -> Result<String, DecodeError> {
            let len = self.u32()? as usize;
            if len == 0 { return Err(DecodeError::BadString); }
            let padded = (len + 3) & !3;
            let bytes = self.take(padded)?;
            if bytes[len - 1] != 0 { return Err(DecodeError::BadString); }
            std::str::from_utf8(&bytes[..len - 1])
                .map(|s| s.to_string())
                .map_err(|_| DecodeError::BadString)
        }
        pub fn array_u32(&mut self) -> Result<Vec<u32>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.u32()?); }
            Ok(v)
        }
        pub fn array_i32(&mut self) -> Result<Vec<i32>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.i32()?); }
            Ok(v)
        }
        pub fn array_u64(&mut self) -> Result<Vec<u64>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.u64()?); }
            Ok(v)
        }
        pub fn array_i64(&mut self) -> Result<Vec<i64>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.i64()?); }
            Ok(v)
        }
        pub fn array_f32(&mut self) -> Result<Vec<f32>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.f32()?); }
            Ok(v)
        }
        pub fn array_f64(&mut self) -> Result<Vec<f64>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(1024));
            for _ in 0..n { v.push(self.f64()?); }
            Ok(v)
        }
        pub fn array_string(&mut self) -> Result<Vec<String>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(64));
            for _ in 0..n { v.push(self.string()?); }
            Ok(v)
        }
        pub fn kv_list(&mut self) -> Result<Vec<(String, String)>, DecodeError> {
            let n = self.u32()? as usize;
            let mut v = Vec::with_capacity(n.min(64));
            for _ in 0..n {
                let k = self.string()?;
                let val = self.string()?;
                v.push((k, val));
            }
            Ok(v)
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum EventIn {
    Init {
        spawn_version: u32,
        extent_w: u32,
        extent_h: u32,
        extent_mode: u32,
        settings: Vec<(String, String)>,
    },
    SettingChanged {
        settings: Vec<(String, String)>,
    },
    Play,
    Pause,
    PointerMotion {
        x: f32,
        y: f32,
        timestamp_us: u64,
        modifiers: u32,
    },
    SetFps {
        fps: u32,
    },
    Shutdown,
    NegotiateBuffers {
        fourcc: u32,
        modifier: u64,
        plane_count: u32,
        sync_mode: u32,
        color: u32,
        mem_hint: u32,
        count: u32,
        path: u32,
        mem_source: u32,
    },
    PointerButton {
        x: f32,
        y: f32,
        button: u32,
        state: u32,
        timestamp_us: u64,
        modifiers: u32,
    },
    PointerAxis {
        x: f32,
        y: f32,
        delta_x: f32,
        delta_y: f32,
        source: u32,
        timestamp_us: u64,
        modifiers: u32,
    },
}

impl EventIn {
    pub fn opcode(&self) -> u16 {
        match self {
            Self::Init { .. } => opcode::event_in::INIT,
            Self::SettingChanged { .. } => opcode::event_in::SETTING_CHANGED,
            Self::Play => opcode::event_in::PLAY,
            Self::Pause => opcode::event_in::PAUSE,
            Self::PointerMotion { .. } => opcode::event_in::POINTER_MOTION,
            Self::SetFps { .. } => opcode::event_in::SET_FPS,
            Self::Shutdown => opcode::event_in::SHUTDOWN,
            Self::NegotiateBuffers { .. } => opcode::event_in::NEGOTIATE_BUFFERS,
            Self::PointerButton { .. } => opcode::event_in::POINTER_BUTTON,
            Self::PointerAxis { .. } => opcode::event_in::POINTER_AXIS,
        }
    }

    pub fn expected_fds(&self) -> u32 {
        match self {
            Self::Init { .. } => 0,
            Self::SettingChanged { .. } => 0,
            Self::Play => 0,
            Self::Pause => 0,
            Self::PointerMotion { .. } => 0,
            Self::SetFps { .. } => 0,
            Self::Shutdown => 0,
            Self::NegotiateBuffers { .. } => 0,
            Self::PointerButton { .. } => 0,
            Self::PointerAxis { .. } => 0,
        }
    }

    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Init { spawn_version, extent_w, extent_h, extent_mode, settings } => {
                wire::w_u32(buf, *spawn_version);
                wire::w_u32(buf, *extent_w);
                wire::w_u32(buf, *extent_h);
                wire::w_u32(buf, *extent_mode);
                wire::w_kv_list(buf, settings);
            }
            Self::SettingChanged { settings } => {
                wire::w_kv_list(buf, settings);
            }
            Self::Play => {}
            Self::Pause => {}
            Self::PointerMotion { x, y, timestamp_us, modifiers } => {
                wire::w_f32(buf, *x);
                wire::w_f32(buf, *y);
                wire::w_u64(buf, *timestamp_us);
                wire::w_u32(buf, *modifiers);
            }
            Self::SetFps { fps } => {
                wire::w_u32(buf, *fps);
            }
            Self::Shutdown => {}
            Self::NegotiateBuffers { fourcc, modifier, plane_count, sync_mode, color, mem_hint, count, path, mem_source } => {
                wire::w_u32(buf, *fourcc);
                wire::w_u64(buf, *modifier);
                wire::w_u32(buf, *plane_count);
                wire::w_u32(buf, *sync_mode);
                wire::w_u32(buf, *color);
                wire::w_u32(buf, *mem_hint);
                wire::w_u32(buf, *count);
                wire::w_u32(buf, *path);
                wire::w_u32(buf, *mem_source);
            }
            Self::PointerButton { x, y, button, state, timestamp_us, modifiers } => {
                wire::w_f32(buf, *x);
                wire::w_f32(buf, *y);
                wire::w_u32(buf, *button);
                wire::w_u32(buf, *state);
                wire::w_u64(buf, *timestamp_us);
                wire::w_u32(buf, *modifiers);
            }
            Self::PointerAxis { x, y, delta_x, delta_y, source, timestamp_us, modifiers } => {
                wire::w_f32(buf, *x);
                wire::w_f32(buf, *y);
                wire::w_f32(buf, *delta_x);
                wire::w_f32(buf, *delta_y);
                wire::w_u32(buf, *source);
                wire::w_u64(buf, *timestamp_us);
                wire::w_u32(buf, *modifiers);
            }
        }
    }

    pub fn decode(opcode: u16, body: &[u8]) -> Result<Self, DecodeError> {
        let mut r = wire::R::new(body);
        let v = match opcode {
            opcode::event_in::INIT => {
                let spawn_version = r.u32()?;
                let extent_w = r.u32()?;
                let extent_h = r.u32()?;
                let extent_mode = r.u32()?;
                let settings = r.kv_list()?;
                Self::Init {
                    spawn_version,
                    extent_w,
                    extent_h,
                    extent_mode,
                    settings,
                }
            }
            opcode::event_in::SETTING_CHANGED => {
                let settings = r.kv_list()?;
                Self::SettingChanged {
                    settings,
                }
            }
            opcode::event_in::PLAY => {
                Self::Play
            }
            opcode::event_in::PAUSE => {
                Self::Pause
            }
            opcode::event_in::POINTER_MOTION => {
                let x = r.f32()?;
                let y = r.f32()?;
                let timestamp_us = r.u64()?;
                let modifiers = r.u32()?;
                Self::PointerMotion {
                    x,
                    y,
                    timestamp_us,
                    modifiers,
                }
            }
            opcode::event_in::SET_FPS => {
                let fps = r.u32()?;
                Self::SetFps {
                    fps,
                }
            }
            opcode::event_in::SHUTDOWN => {
                Self::Shutdown
            }
            opcode::event_in::NEGOTIATE_BUFFERS => {
                let fourcc = r.u32()?;
                let modifier = r.u64()?;
                let plane_count = r.u32()?;
                let sync_mode = r.u32()?;
                let color = r.u32()?;
                let mem_hint = r.u32()?;
                let count = r.u32()?;
                let path = r.u32()?;
                let mem_source = r.u32()?;
                Self::NegotiateBuffers {
                    fourcc,
                    modifier,
                    plane_count,
                    sync_mode,
                    color,
                    mem_hint,
                    count,
                    path,
                    mem_source,
                }
            }
            opcode::event_in::POINTER_BUTTON => {
                let x = r.f32()?;
                let y = r.f32()?;
                let button = r.u32()?;
                let state = r.u32()?;
                let timestamp_us = r.u64()?;
                let modifiers = r.u32()?;
                Self::PointerButton {
                    x,
                    y,
                    button,
                    state,
                    timestamp_us,
                    modifiers,
                }
            }
            opcode::event_in::POINTER_AXIS => {
                let x = r.f32()?;
                let y = r.f32()?;
                let delta_x = r.f32()?;
                let delta_y = r.f32()?;
                let source = r.u32()?;
                let timestamp_us = r.u64()?;
                let modifiers = r.u32()?;
                Self::PointerAxis {
                    x,
                    y,
                    delta_x,
                    delta_y,
                    source,
                    timestamp_us,
                    modifiers,
                }
            }
            other => return Err(DecodeError::UnknownOpcode(other)),
        };
        if !r.at_end() { return Err(DecodeError::Trailing); }
        Ok(v)
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    Ready {
        drm_render_major: u32,
        drm_render_minor: u32,
    },
    BindBuffers {
        generation: u64,
        flags: u32,
        count: u32,
        fourcc: u32,
        width: u32,
        height: u32,
        modifier: u64,
        planes_per_buffer: u32,
        stride: Vec<u32>,
        plane_offset: Vec<u32>,
        size: Vec<u64>,
    },
    FrameReady {
        image_index: u32,
        seq: u64,
        ts_ns: u64,
        release_point: u64,
    },
    Error {
        msg: String,
    },
    ReleaseSyncobj,
    FormatCaps {
        fourccs: Vec<u32>,
        mod_counts: Vec<u32>,
        modifiers: Vec<u64>,
        plane_counts: Vec<u32>,
        device_uuid: Vec<u32>,
        driver_uuid: Vec<u32>,
        drm_render_major: u32,
        drm_render_minor: u32,
        mem_hints: u32,
        sync_caps: u32,
        color_caps: u32,
        extent_max_w: u32,
        extent_max_h: u32,
    },
    BindFailed {
        fourcc: u32,
        modifier: u64,
        reason: u32,
        message: String,
    },
    InitNack {
        received_spawn_version: u32,
        supported_spawn_version: u32,
        reason: String,
    },
    ReportState {
        state: Vec<(String, String)>,
    },
}

impl Event {
    pub fn opcode(&self) -> u16 {
        match self {
            Self::Ready { .. } => opcode::event::READY,
            Self::BindBuffers { .. } => opcode::event::BIND_BUFFERS,
            Self::FrameReady { .. } => opcode::event::FRAME_READY,
            Self::Error { .. } => opcode::event::ERROR,
            Self::ReleaseSyncobj => opcode::event::RELEASE_SYNCOBJ,
            Self::FormatCaps { .. } => opcode::event::FORMAT_CAPS,
            Self::BindFailed { .. } => opcode::event::BIND_FAILED,
            Self::InitNack { .. } => opcode::event::INIT_NACK,
            Self::ReportState { .. } => opcode::event::REPORT_STATE,
        }
    }

    pub fn expected_fds(&self) -> u32 {
        match self {
            Self::Ready { .. } => 0,
            Self::BindBuffers { count, planes_per_buffer, .. } => (*count as u64 * *planes_per_buffer as u64) as u32,
            Self::FrameReady { .. } => 1,
            Self::Error { .. } => 0,
            Self::ReleaseSyncobj => 1,
            Self::FormatCaps { .. } => 0,
            Self::BindFailed { .. } => 0,
            Self::InitNack { .. } => 0,
            Self::ReportState { .. } => 0,
        }
    }

    pub fn encode(&self, buf: &mut Vec<u8>) {
        match self {
            Self::Ready { drm_render_major, drm_render_minor } => {
                wire::w_u32(buf, *drm_render_major);
                wire::w_u32(buf, *drm_render_minor);
            }
            Self::BindBuffers { generation, flags, count, fourcc, width, height, modifier, planes_per_buffer, stride, plane_offset, size } => {
                wire::w_u64(buf, *generation);
                wire::w_u32(buf, *flags);
                wire::w_u32(buf, *count);
                wire::w_u32(buf, *fourcc);
                wire::w_u32(buf, *width);
                wire::w_u32(buf, *height);
                wire::w_u64(buf, *modifier);
                wire::w_u32(buf, *planes_per_buffer);
                wire::w_array_u32(buf, stride);
                wire::w_array_u32(buf, plane_offset);
                wire::w_array_u64(buf, size);
            }
            Self::FrameReady { image_index, seq, ts_ns, release_point } => {
                wire::w_u32(buf, *image_index);
                wire::w_u64(buf, *seq);
                wire::w_u64(buf, *ts_ns);
                wire::w_u64(buf, *release_point);
            }
            Self::Error { msg } => {
                wire::w_string(buf, msg);
            }
            Self::ReleaseSyncobj => {}
            Self::FormatCaps { fourccs, mod_counts, modifiers, plane_counts, device_uuid, driver_uuid, drm_render_major, drm_render_minor, mem_hints, sync_caps, color_caps, extent_max_w, extent_max_h } => {
                wire::w_array_u32(buf, fourccs);
                wire::w_array_u32(buf, mod_counts);
                wire::w_array_u64(buf, modifiers);
                wire::w_array_u32(buf, plane_counts);
                wire::w_array_u32(buf, device_uuid);
                wire::w_array_u32(buf, driver_uuid);
                wire::w_u32(buf, *drm_render_major);
                wire::w_u32(buf, *drm_render_minor);
                wire::w_u32(buf, *mem_hints);
                wire::w_u32(buf, *sync_caps);
                wire::w_u32(buf, *color_caps);
                wire::w_u32(buf, *extent_max_w);
                wire::w_u32(buf, *extent_max_h);
            }
            Self::BindFailed { fourcc, modifier, reason, message } => {
                wire::w_u32(buf, *fourcc);
                wire::w_u64(buf, *modifier);
                wire::w_u32(buf, *reason);
                wire::w_string(buf, message);
            }
            Self::InitNack { received_spawn_version, supported_spawn_version, reason } => {
                wire::w_u32(buf, *received_spawn_version);
                wire::w_u32(buf, *supported_spawn_version);
                wire::w_string(buf, reason);
            }
            Self::ReportState { state } => {
                wire::w_kv_list(buf, state);
            }
        }
    }

    pub fn decode(opcode: u16, body: &[u8]) -> Result<Self, DecodeError> {
        let mut r = wire::R::new(body);
        let v = match opcode {
            opcode::event::READY => {
                let drm_render_major = r.u32()?;
                let drm_render_minor = r.u32()?;
                Self::Ready {
                    drm_render_major,
                    drm_render_minor,
                }
            }
            opcode::event::BIND_BUFFERS => {
                let generation = r.u64()?;
                let flags = r.u32()?;
                let count = r.u32()?;
                let fourcc = r.u32()?;
                let width = r.u32()?;
                let height = r.u32()?;
                let modifier = r.u64()?;
                let planes_per_buffer = r.u32()?;
                let stride = r.array_u32()?;
                let plane_offset = r.array_u32()?;
                let size = r.array_u64()?;
                Self::BindBuffers {
                    generation,
                    flags,
                    count,
                    fourcc,
                    width,
                    height,
                    modifier,
                    planes_per_buffer,
                    stride,
                    plane_offset,
                    size,
                }
            }
            opcode::event::FRAME_READY => {
                let image_index = r.u32()?;
                let seq = r.u64()?;
                let ts_ns = r.u64()?;
                let release_point = r.u64()?;
                Self::FrameReady {
                    image_index,
                    seq,
                    ts_ns,
                    release_point,
                }
            }
            opcode::event::ERROR => {
                let msg = r.string()?;
                Self::Error {
                    msg,
                }
            }
            opcode::event::RELEASE_SYNCOBJ => {
                Self::ReleaseSyncobj
            }
            opcode::event::FORMAT_CAPS => {
                let fourccs = r.array_u32()?;
                let mod_counts = r.array_u32()?;
                let modifiers = r.array_u64()?;
                let plane_counts = r.array_u32()?;
                let device_uuid = r.array_u32()?;
                let driver_uuid = r.array_u32()?;
                let drm_render_major = r.u32()?;
                let drm_render_minor = r.u32()?;
                let mem_hints = r.u32()?;
                let sync_caps = r.u32()?;
                let color_caps = r.u32()?;
                let extent_max_w = r.u32()?;
                let extent_max_h = r.u32()?;
                Self::FormatCaps {
                    fourccs,
                    mod_counts,
                    modifiers,
                    plane_counts,
                    device_uuid,
                    driver_uuid,
                    drm_render_major,
                    drm_render_minor,
                    mem_hints,
                    sync_caps,
                    color_caps,
                    extent_max_w,
                    extent_max_h,
                }
            }
            opcode::event::BIND_FAILED => {
                let fourcc = r.u32()?;
                let modifier = r.u64()?;
                let reason = r.u32()?;
                let message = r.string()?;
                Self::BindFailed {
                    fourcc,
                    modifier,
                    reason,
                    message,
                }
            }
            opcode::event::INIT_NACK => {
                let received_spawn_version = r.u32()?;
                let supported_spawn_version = r.u32()?;
                let reason = r.string()?;
                Self::InitNack {
                    received_spawn_version,
                    supported_spawn_version,
                    reason,
                }
            }
            opcode::event::REPORT_STATE => {
                let state = r.kv_list()?;
                Self::ReportState {
                    state,
                }
            }
            other => return Err(DecodeError::UnknownOpcode(other)),
        };
        if !r.at_end() { return Err(DecodeError::Trailing); }
        Ok(v)
    }
}

